music/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from . import views

app_name = 'music'

urlpatterns=[

    #/music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    #/music/register/
    url(r'^register/$', views.UserFormView.as_view(), name='register'),    

    #/music/login/
    url(r'^login/$', login, {'template_name':'music/login.html'}, name='login'),

    #/music/logout/
    url(r'^logout/$', logout, name='logout'),

    #music/album/add/
    url(r'^album/add/$' , views.AlbumCreate.as_view(), name='album-add'),

    #/music/<pk>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    #music/album/<pk>/
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),

    #music/album/<pk>/delete/
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

    # music/album/<pk>/like/
    url(r'^album/(?P<pk>[0-9]+)/like/$', views.Like.as_view(), name='album-like'),

    # music/album/<pk>/dislike/
    url(r'^album/(?P<pk>[0-9]+)/dislike/$', views.Dislike.as_view(), name='album-dislike'),

    ]

website/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static 
from django.contrib import admin

from rest_framework.urlpatterns import format_suffix_patterns

from music import views

urlpatterns = [
    url('^$', views.Home),
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^albums/', views.AlbumList.as_view()),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)	

music/models.py
from django.db import models
from django.urls import reverse

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    likes = models.IntegerField(default=1)
    dislikes = models.IntegerField(default=1)

    def get_absolute_url(self):
        return reverse('music:detail',  kwargs={ 'pk':self.pk } )

    def __str__(self):
        return self.album_title+' - '+self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'email', 'password']
		

music/views.py
from django.views.generic import View, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy
from django.http.response import HttpResponse

from rest_framework.views import APIView
from rest_framework.response import Response

from .models import Album
from .forms import UserForm
from .serializers import AlbumSerializer

def Home(request):
	return render(request, 'music/home.html')

class IndexView(ListView):
	template_name='music/index.html'
	context_object_name = 'all_albums'

	def get_queryset(self):
		return sorted(list(Album.objects.all()), key=lambda x:x.likes/x.dislikes ,reverse=True)


class DetailView(DetailView):
	model = Album
	template_name = 'music/detail.html'


class AlbumCreate(CreateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
	model = Album
	success_url = reverse_lazy('music:index')

class Like(View):
	def post(self,request,pk):
		a = Album.objects.filter(pk=pk)[0]
		a.likes += 1
		a.save()
		#return redirect('music:detail', pk=pk)
		return redirect('music:index')

class Dislike(View):
	def post(self,request,pk):
		a = Album.objects.filter(pk=pk)[0]
		a.dislikes += 1
		a.save()
		return redirect('music:index')

class UserFormView(View):
	form_class = UserForm
	template_name = 'music/registration_form.html'

	# display blank form
	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form':form})

	# process form data
	def post(self, request):
		form = self.form_class(request.POST)

		if form.is_valid():
			user = form.save(commit=False)

			# cleaning data
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()
			
			user = authenticate(username=username, password=password)
			
			if user is not None:
				if user.is_active:
					 login(request,user)
					 return redirect('music:index')

		return render(request, self.template_name, {'form':form})

# List All albums or create a new one
# alnums/
class AlbumList(APIView):
	def get(self, request):
		albums = Album.objects.all()
		serializer = AlbumSerializer(albums, many=True)
		return Response(serializer.data)

	def post(self):
		pass

music/templates/music/album_form.html
{% extends 'music/form-box.html' %}

{% block title %} Add Album {% endblock %}
{% block albums_active %} active {% endblock %}

{% block heading %} Add a new Album {% endblock %}

music/templates/music/base.html
 <!DOCTYPE html>
<html>
	<head>
		<title> {% block title %} DangerDon {% endblock %} </title>
		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'music/css/font-awesome.min.css' %}">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
		
		<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Satisfy" />
		<link rel="stylesheet" type="text/css" href="{% static 'music/css/base.css' %}" >

		{% block includes %}
		{% endblock %}

	</head>
	<body>
		

		<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
				<a class="navbar-brand" href=" {% url 'music:index' %} ">DangerDon</a>

				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#topNavBar">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="topNavBar">
					<div class="navbar-nav">
							
							<a class="nav-item nav-link {% block albums_active %}{% endblock %}" href=" {% url 'music:index'  %} ">
								<i class="fa fa-windows" aria-hidden="true"></i>	
								&nbsp;Albums
							</a>
							<a class="nav-item nav-link {% block songs_active %}{% endblock %}" href=" {% url 'music:index'  %} ">
								<i class="fa fa-music" aria-hidden="true"></i>	
								&nbsp;Songs
							</a>

					</div>
					<form class="form-inline ml-lg-5" role="search" meathod="get" action="#">
						<input class="form-control mr-sm-2" type="search" name="q" value="" placeholder="Search">
						<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
					</form>

					<div class="navbar-nav navbar-toggler-right ml-auto">
						<a class="nav-item nav-link " href=" {% url 'music:album-add' %} ">
								<i class="fa fa-plus" aria-hidden="true"></i>	
								&nbsp;Add Albums
							</a>
							<a class="nav-item nav-link " href=" {% url 'music:logout'  %} ">
								<i class="fa fa-power-off" aria-hidden="true"></i>	
								&nbsp;Log Out
						</a>
					</div>
				


				</div>









		</nav>



		{% block body %}
		{% endblock %}


		
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
	</body>
</html>

music/templates/music/card.html
<div class="card m-2">
	<div class="container">
		<a href="{% url 'music:detail' album.id %}">	
			<img src="{{ album.album_logo.url }}" class="card-img my-3 img-responsive" alt=" {{album.album_title}} "> 
		</a>
		<div class="card-block m-1">
			<h4 class="card-title"> {{ album.album_title }} </h4>
			<h6 class="card-subtitle text-muted"> {{ album.artist }}</h6>
			<div class="row my-2">
				<a href=" {% url 'music:detail' album.id %} " class="btn btn-primary mr-1">View Details</a>

				<form action=" {% url 'music:album-delete' album.id %} " method="post">
					{% csrf_token %}
					<button class="btn btn-outline-secondary mr-1 fa fa-trash-o" type="submit"></button>
                </form>
                <form action="{% url 'music:album-like' album.id %}" method="post">
                    {% csrf_token %}
				    <button class="btn btn-outline-secondary mr-1 fa fa-thumbs-o-up" type="submit"></button>
                </form>
                <form action="{% url 'music:album-dislike' album.id %}" method="post">
                    {% csrf_token %}
				    <button class="btn btn-outline-secondary mr-1 fa fa-thumbs-o-down" type="submit"></button>
                </form>
			</div>
		</div>
	</div>				
</div>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %} Album Details {% endblock %}
{% block songs_active %} active {% endblock %}

{% block body %}

	{% include 'music/card.html' %}	

	{% for song in album.song_set.all %}
		{{ song.song_title }}
		<br />
	{% endfor %}


{% endblock %}

music/templates/music/form-box.html
{% extends 'music/base.html' %}

{% block body %}
<div class="container-fluid">
	<div class="card col-sm-12 col-md-9 col-lg-7 my-3">
		<div class="card-block mt-4     ">
			<div class="card-header">
				<h4> {% block heading %} Heading Here {% endblock %} </h4>
			</div>
			<form  action="" method="POST" enctype="multipart/form-data" class="my-3">
				{% csrf_token %}
				{% include 'music/form-template.html' %}

				<div class="form-group">
					 <button class="btn btn-success" type="submit">Submit</button>
				</div>
			</form>

		</div>
	</div>
</div>
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
	<div class="form-group">
		<!--div class="offset-sm-2 col-sm-10">
			<span class="text-danger small" >{{ field.errors }}</span>
		</div-->	
		<div class="row">
			<label class="control-label col-sm-3">{{ field.label_tag }} </label>
			<div class="col-sm-9">{{ field }}</div>
		</div>	
	</div>
{% endfor %}

music/templates/music/home.html
<html>
    <head>
        <title> DangerDon </title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'music/css/font-awesome.min.css' %}">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

		<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Satisfy" />
		<link rel="stylesheet" type="text/css" href="{% static 'music/css/home.css' %}" >
    </head>
    <body>

    Hello

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    </body>
</html>

music/templates/music/index.html
{% extends 'music/base.html' %}
{% load static %}

{% block albums_active %} active {% endblock %}
{% load static %}

{% block includes %}
	<link rel="stylesheet" type="text/css" href=" {% static 'music/css/index.css' %} ">
{% endblock %}


{% block body %}

	<div class="container-fluid ">
		<div class="row" >	 
			{% for album in all_albums %}

				{% include 'music/card.html' %}	

			{% endfor %}
		</div>
	</div>

{% endblock %}

<!--  col-md-3 col-sm-4 -->

music/templates/music/login.html
{% extends 'music/form-box.html' %}

{% block title %} Log In {% endblock %}

{% block heading %} Login Here {% endblock %}

music/templates/music/registration_form.html
{% extends 'music/form-box.html' %}

{% block title %} Register {% endblock %}

{% block heading %} Register as new user {% endblock %}